### ISSUE TITLE
Unclear how to use examples 

### ISSUE THREAD

**Issue by aarongerber** [int8/gomcts#1]
It may be my lack of Go knowledge, but it is unclear to me how to see tic tac toe example in action. Could you provide guidance in the readme and/or create an example file and explain how to launch it?

**Comment by kynrai** [comment]
Just create a new go file with this gomcts code as an import. The new go file can be in another package. here is what I did, outside of the go path.
```
git clone git@github.com/int8/gomcts.git
cd gomtcs
go mod init github.com/int8.gomcts
mkdir cmd/ttt && touch cmd/ttt/main.go

<paste in code below>

go run cmd/ttt/main.go
```

```go
package main

import (
	"log"

	"github.com/int8/gomcts"
)

func main() {
	initialState := gomcts.CreateTicTacToeInitialGameState(3)
	chosenAction := gomcts.MonteCarloTreeSearch(initialState, gomcts.DefaultRolloutPolicy, 100)
	log.Println(chosenAction)
}

```
